export const styles = {
  page: {
    minHeight: "100vh",
    background: "#0B1B33",
    padding: "24px 16px",
    fontFamily: "Georgia, 'Times New Roman', serif",
    color: "#F2EEE3",
  },
  container: { maxWidth: 480, margin: "0 auto" },
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 4 },
  monogram: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    border: "1px solid #C9A24B",
    color: "#C9A24B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 15,
    letterSpacing: 1,
    flexShrink: 0,
  },
  brand: { fontSize: 14, letterSpacing: 2, color: "#F2EEE3" },
  tagline: { fontSize: 12, color: "#C9A24B", fontStyle: "italic", marginTop: 2 },
  verseAnchor: {
    fontSize: 13,
    color: "#8FA0BF",
    fontStyle: "italic",
    margin: "16px 0 8px",
    borderLeft: "2px solid #C9A24B",
    paddingLeft: 10,
  },
  verseLink: {
    fontWeight: 300,
    color: "#6B7A99",
    fontSize: 12,
  },
  pitch: {
    fontSize: 13,
    color: "#C9A24B",
    lineHeight: 1.5,
    margin: "0 0 24px",
  },
  card: {
    background: "#12294A",
    borderRadius: 10,
    padding: 20,
    border: "1px solid rgba(201,162,75,0.25)",
  },
  label: {
    display: "block",
    fontSize: 13,
    color: "#C9A24B",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  textarea: {
    width: "100%",
    background: "#0B1B33",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 6,
    color: "#F2EEE3",
    padding: 12,
    fontSize: 15,
    fontFamily: "inherit",
    resize: "vertical",
    boxSizing: "border-box",
  },
  button: {
    width: "100%",
    marginTop: 14,
    padding: "12px 0",
    background: "#C9A24B",
    color: "#0B1B33",
    border: "none",
    borderRadius: 6,
    fontSize: 15,
    fontWeight: "bold",
    letterSpacing: 0.5,
    fontFamily: "inherit",
  },
  input: {
    width: "100%",
    background: "#0B1B33",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 6,
    color: "#F2EEE3",
    padding: 12,
    fontSize: 15,
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  usageNote: { fontSize: 12, color: "#8FA0BF", marginTop: 10, textAlign: "center" },
  creatorNote: { fontSize: 13, color: "#C9A24B", marginTop: 10, textAlign: "center", fontWeight: "bold" },
  unlockLink: {
    fontSize: 11,
    color: "#6B7A99",
    textAlign: "center",
    marginTop: 6,
    textDecoration: "underline",
    cursor: "pointer",
  },
  unlockRow: { display: "flex", gap: 8, marginTop: 8 },
  unlockInput: {
    flex: 1,
    background: "#0B1B33",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 6,
    color: "#F2EEE3",
    padding: 8,
    fontSize: 13,
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  unlockButton: {
    background: "#C9A24B",
    color: "#0B1B33",
    border: "none",
    borderRadius: 6,
    padding: "0 14px",
    fontSize: 13,
    fontWeight: "bold",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  paywall: {
    marginTop: 16,
    padding: 14,
    background: "rgba(201,162,75,0.1)",
    border: "1px solid rgba(201,162,75,0.4)",
    borderRadius: 8,
  },
  paywallTitle: { color: "#C9A24B", fontWeight: "bold", margin: "0 0 6px", fontSize: 14 },
  paywallText: { color: "#F2EEE3", fontSize: 13, margin: 0, lineHeight: 1.5 },
  error: { color: "#E08585", fontSize: 13, marginTop: 10 },
  resultCard: {
    background: "#12294A",
    borderRadius: 10,
    padding: 20,
    marginTop: 20,
    border: "1px solid rgba(201,162,75,0.25)",
  },
  verseTag: {
    color: "#C9A24B",
    fontSize: 13,
    fontStyle: "italic",
    marginBottom: 16,
    textAlign: "center",
  },
  blockHeading: {
    color: "#C9A24B",
    fontSize: 13,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    margin: "18px 0 10px",
    borderBottom: "1px solid rgba(201,162,75,0.25)",
    paddingBottom: 6,
  },
  block: { marginBottom: 14 },
  blockLabelRow: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  blockLabel: { color: "#8FA0BF", fontSize: 11, letterSpacing: 1, textTransform: "uppercase" },
  miniScore: {
    fontSize: 11,
    color: "#C9A24B",
    fontWeight: "bold",
    background: "rgba(201,162,75,0.12)",
    padding: "2px 8px",
    borderRadius: 10,
  },
  blockText: { color: "#F2EEE3", fontSize: 15, lineHeight: 1.5, margin: "4px 0 0" },
  coachNote: {
    color: "#8FA0BF",
    fontSize: 12,
    fontStyle: "italic",
    margin: "6px 0 0",
    lineHeight: 1.4,
  },
  coachingPanel: {
    marginTop: 18,
    paddingTop: 14,
    borderTop: "1px solid rgba(201,162,75,0.25)",
  },
  coachingHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "#C9A24B",
    fontSize: 13,
    letterSpacing: 0.5,
  },
  scoreGlobal: {
    fontSize: 18,
    fontWeight: "bold",
  },
  modeGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  modeCard: {
    background: "#12294A",
    borderRadius: 10,
    padding: 18,
    border: "1px solid rgba(201,162,75,0.25)",
    display: "block",
    textDecoration: "none",
    cursor: "pointer",
  },
  modeCardDisabled: {
    background: "#12294A",
    borderRadius: 10,
    padding: 18,
    border: "1px solid rgba(201,162,75,0.12)",
    opacity: 0.5,
    cursor: "not-allowed",
    pointerEvents: "none",
  },
  modeCardHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  modeCardTitle: {
    fontSize: 16,
    color: "#F2EEE3",
    fontWeight: "bold",
    letterSpacing: 0.3,
  },
  modeCardDescription: {
    fontSize: 13,
    color: "#8FA0BF",
    lineHeight: 1.5,
    margin: "0 0 12px",
  },
  modeCardAction: {
    display: "inline-block",
    background: "#C9A24B",
    color: "#0B1B33",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  modeBadgeAvailable: {
    fontSize: 10,
    letterSpacing: 0.5,
    color: "#C9A24B",
    border: "1px solid rgba(201,162,75,0.4)",
    borderRadius: 20,
    padding: "3px 10px",
    textTransform: "uppercase",
  },
  modeBadgeSoon: {
    fontSize: 10,
    letterSpacing: 0.5,
    color: "#8FA0BF",
    border: "1px solid rgba(143,160,191,0.3)",
    borderRadius: 20,
    padding: "3px 10px",
    textTransform: "uppercase",
  },
  copyButton: {
    background: "transparent",
    color: "#C9A24B",
    border: "1px solid rgba(201,162,75,0.4)",
    borderRadius: 6,
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: "bold",
    fontFamily: "inherit",
    cursor: "pointer",
    letterSpacing: 0.3,
  },
  copyButtonRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: 10,
  },
  storyTitle: {
    fontSize: 20,
    color: "#F2EEE3",
    fontWeight: "bold",
    margin: "4px 0 8px",
  },
  storyResume: {
    fontSize: 14,
    color: "#8FA0BF",
    fontStyle: "italic",
    lineHeight: 1.5,
    margin: "0 0 16px",
  },
  storyCharactersRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 18,
  },
  storyCharacterChip: {
    fontSize: 12,
    color: "#F2EEE3",
    background: "rgba(201,162,75,0.12)",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 20,
    padding: "4px 12px",
  },
  storySceneCard: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottom: "1px solid rgba(201,162,75,0.2)",
  },
  storySceneHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 6,
  },
  storySceneNumber: {
    fontSize: 12,
    color: "#C9A24B",
    fontWeight: "bold",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  storySceneMeta: {
    fontSize: 11,
    color: "#8FA0BF",
  },
  storySceneVisual: {
    fontSize: 13,
    color: "#8FA0BF",
    fontStyle: "italic",
    margin: "4px 0 8px",
    lineHeight: 1.5,
  },
  storySceneAction: {
    fontSize: 15,
    color: "#F2EEE3",
    lineHeight: 1.5,
    margin: "0 0 8px",
  },
  storyDialogueLine: {
    fontSize: 14,
    color: "#F2EEE3",
    lineHeight: 1.5,
    margin: "0 0 4px",
    paddingLeft: 12,
    borderLeft: "2px solid rgba(201,162,75,0.3)",
  },
  storyDialogueName: {
    color: "#C9A24B",
    fontWeight: "bold",
  },
  storyMessageFinal: {
    marginTop: 18,
    paddingTop: 14,
    borderTop: "1px solid rgba(201,162,75,0.25)",
    fontSize: 15,
    color: "#F2EEE3",
    lineHeight: 1.6,
  },
  storySceneTechnical: {
    fontSize: 12,
    color: "#C9A24B",
    fontStyle: "italic",
    margin: "0 0 8px",
    lineHeight: 1.5,
  },
};
